# compiles all micro server files

all: micro-client micro-server micro-translator micro-currency micro-voting

micro-client: micro-client.c
	gcc -o micro-client micro-client.c

micro-server: micro-server.c
	gcc -o micro-server micro-server.c

micro-translator: micro-translator.c
	gcc -o micro-translator micro-translator.c

micro-currency: micro-currency.c
	gcc -o micro-currency micro-currency.c

micro-voting: micro-voting.c
	gcc -o micro-voting micro-voting.c