package GUI;

import DatabaseControllers.DataBaseManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author henriqueandras
 */
public class LoginPageGUI extends javax.swing.JFrame {

    /** Creates new form LoginPageGUI */
    public LoginPageGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PBackground = new javax.swing.JPanel();
        LPageTitle = new javax.swing.JLabel();
        LUserName = new javax.swing.JLabel();
        LPassword = new javax.swing.JLabel();
        TUserName = new javax.swing.JTextField();
        TPassword = new javax.swing.JPasswordField();
        BLogin = new javax.swing.JButton();
        LFailed = new javax.swing.JLabel();
        BCreateAccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BAccessAnonymously = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page Application");
        setBackground(new java.awt.Color(255, 255, 255));

        PBackground.setBackground(new java.awt.Color(51, 153, 255));

        LPageTitle.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 24)); // NOI18N
        LPageTitle.setForeground(new java.awt.Color(255, 255, 255));
        LPageTitle.setText("Login Page");

        LUserName.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        LUserName.setForeground(new java.awt.Color(14, 73, 131));
        LUserName.setText("username");

        LPassword.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        LPassword.setForeground(new java.awt.Color(14, 72, 131));
        LPassword.setText("password");

        TUserName.setBackground(new java.awt.Color(255, 255, 255));
        TUserName.setForeground(new java.awt.Color(153, 153, 153));
        TUserName.setBorder(null);
        TUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUserNameActionPerformed(evt);
            }
        });

        TPassword.setBackground(new java.awt.Color(255, 255, 255));
        TPassword.setForeground(new java.awt.Color(153, 153, 153));
        TPassword.setBorder(null);
        TPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPasswordActionPerformed(evt);
            }
        });

        BLogin.setBackground(new java.awt.Color(255, 204, 0));
        BLogin.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        BLogin.setForeground(new java.awt.Color(255, 255, 255));
        BLogin.setText("Login");
        BLogin.setBorderPainted(false);
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });

        LFailed.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        LFailed.setForeground(new java.awt.Color(255, 0, 0));

        BCreateAccount.setBackground(new java.awt.Color(255, 204, 0));
        BCreateAccount.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 13)); // NOI18N
        BCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        BCreateAccount.setText("Create Account");
        BCreateAccount.setBorderPainted(false);
        BCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCreateAccountActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Don't have an account yet?");

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("or access the website without having an account:");

        BAccessAnonymously.setBackground(new java.awt.Color(255, 204, 0));
        BAccessAnonymously.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        BAccessAnonymously.setForeground(new java.awt.Color(255, 255, 255));
        BAccessAnonymously.setText("Access anonymously");
        BAccessAnonymously.setBorderPainted(false);
        BAccessAnonymously.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAccessAnonymouslyActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PBackgroundLayout = new org.jdesktop.layout.GroupLayout(PBackground);
        PBackground.setLayout(PBackgroundLayout);
        PBackgroundLayout.setHorizontalGroup(
            PBackgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PBackgroundLayout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .add(PBackgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PBackgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(LFailed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 343, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(PBackgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, PBackgroundLayout.createSequentialGroup()
                                .add(LPageTitle)
                                .add(426, 426, 426))
                            .add(PBackgroundLayout.createSequentialGroup()
                                .add(114, 114, 114)
                                .add(BLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(23, 23, 23))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, PBackgroundLayout.createSequentialGroup()
                                .add(PBackgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(LUserName)
                                    .add(LPassword))
                                .add(27, 27, 27)
                                .add(PBackgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(TUserName)
                                    .add(TPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(365, 365, 365))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PBackgroundLayout.createSequentialGroup()
                        .add(PBackgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, PBackgroundLayout.createSequentialGroup()
                                .add(BAccessAnonymously)
                                .add(77, 77, 77))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, PBackgroundLayout.createSequentialGroup()
                                .add(BCreateAccount)
                                .add(88, 88, 88))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, PBackgroundLayout.createSequentialGroup()
                                .add(jLabel1)
                                .add(66, 66, 66)))
                        .add(340, 340, 340))))
        );
        PBackgroundLayout.setVerticalGroup(
            PBackgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PBackgroundLayout.createSequentialGroup()
                .add(77, 77, 77)
                .add(LPageTitle)
                .add(47, 47, 47)
                .add(PBackgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(LUserName)
                    .add(TUserName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(56, 56, 56)
                .add(PBackgroundLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(LPassword)
                    .add(TPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(34, 34, 34)
                .add(BLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(LFailed, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 67, Short.MAX_VALUE)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(BCreateAccount)
                .add(26, 26, 26)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(BAccessAnonymously)
                .add(38, 38, 38))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PBackground, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PBackground, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
        // TODO add your handling code here:
        String username = TUserName.getText();
        String password = TPassword.getText();
        String type = DataBaseManager.getInstance().SelectType(username);
        if(DataBaseManager.getInstance().login(username, password)) {
            if(type.equals("LANDLORD")) {
                LandlordGUI landlord = new LandlordGUI(username);
                landlord.setVisible(true);
                dispose();
            } else if(type.equals("RENTER")) {
                RenterGUI search = new RenterGUI(username);
                search.setVisible(true);
                dispose();
            } else {
                ManagerGUI manager = new ManagerGUI(username);
                manager.setVisible(true);
                dispose();
            }
        } else {
            LFailed.setText("Login failed: no matching username/password.");
        }
    }//GEN-LAST:event_BLoginActionPerformed

    private void TPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TPasswordActionPerformed

    private void BCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCreateAccountActionPerformed
        // TODO add your handling code here:
        CreateAccountGUI create = new CreateAccountGUI();
        create.setVisible(true);
        dispose();
    }//GEN-LAST:event_BCreateAccountActionPerformed

    private void BAccessAnonymouslyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAccessAnonymouslyActionPerformed
        // TODO add your handling code here:
        GeneralUserSearchPageGUI search = new GeneralUserSearchPageGUI();
        search.setVisible(true);
        dispose();
    }//GEN-LAST:event_BAccessAnonymouslyActionPerformed

    private void TUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAccessAnonymously;
    private javax.swing.JButton BCreateAccount;
    private javax.swing.JButton BLogin;
    private javax.swing.JLabel LFailed;
    private javax.swing.JLabel LPageTitle;
    private javax.swing.JLabel LPassword;
    private javax.swing.JLabel LUserName;
    private javax.swing.JPanel PBackground;
    private javax.swing.JPasswordField TPassword;
    private javax.swing.JTextField TUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
